name: iOS Build

on:
  pull_request: { branches: [ main ] }
  push: { branches: [ chore/*, feature/*, fix/* ] }

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"

      - name: Detect project and target
        id: detect
        shell: bash
        run: |
          set -e
          PROJECT=$(ls *.xcodeproj | { grep -E 'Echo\.xcodeproj|SNAPS\.xcodeproj' || cat; } | head -n1)
          echo "project=$PROJECT" >> "$GITHUB_OUTPUT"
          TARGET=$(/usr/bin/xcodebuild -list -project "$PROJECT" | awk '/Targets:/{f=1;next} f&&NF{print;exit}')
          echo "target=$TARGET" >> "$GITHUB_OUTPUT"
          echo "Detected project: $PROJECT"
          echo "Detected target:  $TARGET"

      - name: Build (Debug, generic simulator)
        run: |
          xcodebuild \
            -project "${{ steps.detect.outputs.project }}" \
            -target  "${{ steps.detect.outputs.target }}" \
            -configuration Debug \
            -destination "generic/platform=iOS Simulator" \
            build
